### PR TITLE
Auto moduling

### PR DESCRIPTION
**Pull request by arhitextura**
I made a Python script that takes all the depending GRAPHISOT® Modules which are included in the AddOn project and writes it inside the CMakeLists.txt This this update happens only if the project was built successfully. You can find short description inside the About.md.

### CODE REVIEW

**Comment by kovacsv** [comment]
Thanks for the contribution. I think your tool can be useful for developers who are working primarily on windows, but want to keep their CMakeLists up-to-date.

To merge this tool I recommend some modifications:
- The update process should not part of the build, I would remove it from `CMakeLists.txt`. Most of the time it won't do anything, so I don't think it's a good idea to run it all the time.
- I would move it outside from the Add-On source, more like an external helper tool:
  - The best would be to create a root directory called `Tools`, and place it there.
  - I recommend the following file structure:
    - `/Tools/CMakeListsUpdater/CMakeListsUpdater.py` - Main script file. I think `ModuleTypes.py` can be integrated to this file so you don't have to deal with `__pycache__` files.
    - `/Tools/CMakeListsUpdater/README.md` - the readme for this tool. With this naming convention it will be visible when you navigate to the tool's folder.

**Comment by arhitextura** [comment]
Hi Viktor. Thanks for the indications, I really welcome them since I am a beginner developer.  I will make the changes this week. Also I will do a major cleanup on the solution because it is really messy for now.

**Comment by arhitextura** [comment]
> Most of the time it won't do anything, so I don't think it's a good idea to run it all the time.
> The best would be to create a root directory called Tools, and place it there.  

I was thinking about a batch file which would call the script and I will let python handle the errors.

**Comment by kovacsv** [comment]
@arhitextura, we discussed your issue internally, and found a more future-proof solution. I've just committed a modification to the `CMakeLists.txt`. Now it adds all of the dependencies automatically. It means you don't have to deal with them later, every module will be accessible without any modification.

**Comment by arhitextura** [comment]
> @arhitextura, we discussed your issue internally, and found a more future-proof solution. I've just committed a modification to the `CMakeLists.txt`. Now it adds all of the dependencies automatically. It means you don't have to deal with them later, every module will be accessible without any modification.

I saw it. It is a much cleaner solution. I was thinking about this method, but somehow it felt wrong to include all the paths. Maybe because of this I started to scratch my left ear with my right hand.

**Pull request closed without merging**
